server:
  port: 8071
spring:
  application:
    name: session-manager-service
  sleuth:
    sampler:
      probability: 100
  zipkin:
    base-url: http://localhost:9411/
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




